### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TeaFaris** [Flam3y/Multi_donuts#1]
You have skill issue, go learn some normal languages

**Comment by Flam3y** [comment]
Go for a walk and touch some grass, dot-net fan. Nerd 🤓🤓🤓🤓🤓🤓

**Comment by TeaFaris** [comment]
> Go for a walk and touch some grass, dot-net fan. Nerd 🤓🤓🤓🤓🤓🤓

skill issue

**Comment by Flam3y** [comment]
Nerd issue

**Comment by Flam3y** [comment]
Tea issue

**Comment by TeaFaris** [comment]
> Tea issue

no unit tests issue

**Comment by TeaFaris** [comment]
> Tea issue

slow python issue

**Comment by Flam3y** [comment]
https://docs.python.org/3/library/unittest.html

**Comment by TeaFaris** [comment]
> Tea issue

dynamic typed language issue

**Comment by Flam3y** [comment]
knowledge issue

**Comment by TeaFaris** [comment]
> knowledge issue

no mvc issue

**Comment by Flam3y** [comment]
{} issue

**Comment by Flam3y** [comment]
; issue

**Comment by TeaFaris** [comment]
> ; issue

no semicolon issue

**Comment by Flam3y** [comment]
no Multi-donuts issue

**Comment by Flam3y** [comment]
🤓

**Comment by TeaFaris** [comment]
> no Multi-donuts issue

console graphics plagiat issue

**Comment by Flam3y** [comment]
```
import issue

print(issue.detect("TeaFaris")
```

>>> True)

**Comment by TeaFaris** [comment]
no built-in linq issue

**Comment by Flam3y** [comment]
https://pypi.org/project/py-linq/
